server:
  port: 9003

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: host2
    listener:
      simple:
        acknowledge-mode: manual   # 手动ACK（更好控）
        prefetch: 20               # 一次拉取多少条
        default-requeue-rejected: false  # 失败不回队列（走死信）

  application:
    name: iot-data

  datasource:
    url: jdbc:mysql://localhost:3306/iot_platform?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.user.pojo

iot:
  mq:
    report:
      exchange: iot.report.ex
      routing-key: iot.report
      queue: iot.report.q
      dlx-exchange: iot.report.dlx.ex
      dlq: iot.report.dlq
  report:
      dedup-seconds: 60   # 消费幂等：同一msgId 60秒内只处理一次（可按需调）
  device:
    offline-minutes: 1 #心跳超时时间，如果一个设备，超过 分钟没有上报数据 → 认为它掉线
  alarm:
    temp-high: 30
    humi-high: 80
    battery-low: 20
    dedup-seconds: 60